import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import { spawn } from "node:child_process";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, test } from "vitest";
import { generateImageModelsFile } from "../scripts/generate-image-models.ts";
import type { ImagesModel } from "../src/types.ts";

const SCRIPT_PATH = join(fileURLToPath(import.meta.url), "../../scripts/generate-image-models.ts");

function makeModel(overrides?: Partial<ImagesModel<"openrouter-images">>): ImagesModel<"openrouter-images"> {
	return {
		id: "test/flux",
		name: "Test FLUX",
		api: "openrouter-images",
		provider: "openrouter",
		baseUrl: "https://openrouter.ai/api/v1",
		input: ["text"],
		output: ["image"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		...overrides,
	};
}

describe("generateImageModelsFile", () => {
	test("produces valid TypeScript with correct header and export", () => {
		const output = generateImageModelsFile([makeModel()]);

		expect(output).toContain("// This file is auto-generated by scripts/generate-image-models.ts");
		expect(output).toContain("export const IMAGE_MODELS");
		expect(output).toContain('as const satisfies Record<string, Record<string, ImagesModel<ImagesApi>>>');
	});

	test("serializes a model id and satisfies clause correctly", () => {
		const output = generateImageModelsFile([makeModel({ id: "black-forest-labs/flux.1-schnell" })]);

		expect(output).toContain('"black-forest-labs/flux.1-schnell"');
		expect(output).toContain('satisfies ImagesModel<"openrouter-images">');
	});

	test("sorts models alphabetically by id within the provider block", () => {
		const output = generateImageModelsFile([
			makeModel({ id: "z/last" }),
			makeModel({ id: "a/first" }),
		]);

		const firstIdx = output.indexOf('"a/first"');
		const lastIdx = output.indexOf('"z/last"');
		expect(firstIdx).toBeLessThan(lastIdx);
	});
});

describe("generate-image-models empty-fetch guard", () => {
	test("exits with code 1 and prints an error when the API returns no models", async () => {
		const server = createServer((_req, res) => {
			res.writeHead(200, { "content-type": "application/json" });
			res.end(JSON.stringify({ data: [] }));
		});

		await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
		const { port } = server.address() as AddressInfo;

		try {
			const { exitCode, stderr } = await new Promise<{ exitCode: number | null; stderr: string }>(
				(resolve) => {
					const chunks: Buffer[] = [];
					const child = spawn(
						"node",
						["--experimental-strip-types", SCRIPT_PATH],
						{
							env: { ...process.env, OPENROUTER_MODELS_URL: `http://127.0.0.1:${port}/models` },
						},
					);
					child.stderr.on("data", (chunk: Buffer) => chunks.push(chunk));
					child.on("close", (code) =>
						resolve({ exitCode: code, stderr: Buffer.concat(chunks).toString() }),
					);
				},
			);

			expect(exitCode).toBe(1);
			expect(stderr).toContain("refusing to overwrite");
		} finally {
			await new Promise<void>((resolve, reject) =>
				server.close((err) => (err ? reject(err) : resolve())),
			);
		}
	});
});
